mutation CreateBasket($user_id: ID!, $goods_id: Int, $size: String) {
  create_basket_item(
    data: { user: { id: $user_id }, good: $goods_id, size: $size }
  ) {
    id

    user {
      id
      email
    }

    size

    good {
      id
      name
    }
  }
}
