query GetOrderById($id: ID!) {
  orders_by_id(id: $id) {
    id
    totalPrice
    created_at
    items {
      ...OrderItemFragment
    }

    status

    user {
      first_name
      last_name
      id
      address
      number
    }
  }
}
