query GetHomePage {
  homePage {
    id

    sliderBestsellers {
      id

      goods_id {
        id

        select

        name

        price

        images {
          id
          directus_files_id {
            ...MediaFragment
          }
        }
      }
    }

    newItems {
      id

      goods_id {
        id

        select

        name

        price

        images {
          directus_files_id {
            ...MediaFragment
          }
        }
      }
    }
  }
}
