query GetHomePage {
  homePage {
    id

    mainSlider {
      id
      mainSlider_id {
        id
        title
        decription
        nameButton
        linkButton
        image {
          ...MediaFragment
        }
      }
    }

    sliderBestsellers {
      id

      goods_id {
        id

        select

        name

        price

        images {
          id
          directus_files_id {
            ...MediaFragment
          }
        }
      }
    }

    newItems {
      id

      goods_id {
        id

        select

        name

        price

        images {
          directus_files_id {
            ...MediaFragment
          }
        }
      }
    }
  }
}
