query GetLookBockById($id: ID!) {
  lookBook_by_id(id: $id) {
    id
    title
    description
    markdown

    mainImages {
      id

      directus_files_id {
        ...MediaFragment
      }
    }
  }
}
