query GetGoods($id: ID!) {
  goods_by_id(id: $id) {
    id
    name
    price
    description
    parameters
    select
    image_builder {
      id
      item {
        __typename

        ... on goodsImg {
          img {
            ...MediaFragment
          }
        }
        ... on goodsTwoImages {
          imgOne {
            ...MediaFragment
          }

          imgTwo {
            ...MediaFragment
          }
        }
      }
      collection
    }
  }
}
