query GetFooter {
  footer {
    id

    links {
      id

      footerLinks_id {
        id
        title

        links {
          id

          links_id {
            id
            button_title
            button_links
          }
        }
      }
    }
  }
}
