import type { Metadata } from "next";

import "@/shared/styles/globals.css";
import "@/shared/styles/index.scss";
import { MainLayout } from "@/shared/layout/MainLayout";
import { Providers } from "@/shared/layout/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <MainLayout>{children}</MainLayout>
        </Providers>
      </body>
    </html>
  );
}
